# Generated by Django 4.1 on 2022-08-30 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('body', models.CharField(max_length=10000)),
                ('category', models.CharField(default=None, max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Showbiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('body', models.CharField(max_length=10000)),
                ('category', models.CharField(default='Showbiz', max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('body', models.CharField(max_length=10000)),
                ('category', models.CharField(default='Sport', max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('prefix', models.CharField(blank=True, default=None, max_length=320)),
                ('body', models.CharField(max_length=10000)),
                ('category', models.CharField(default=None, max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('body', models.CharField(max_length=10000)),
                ('category', models.CharField(default='Travel', max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('text_url', models.CharField(max_length=500)),
                ('thumbnail', models.CharField(max_length=500)),
            ],
        ),
    ]
