# Generated by Django 4.1.5 on 2023-01-22 12:46

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerpost',
            name='body2',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='headerpost',
            name='body3',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='headerpost',
            name='image2',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='headerpost',
            name='image3',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='headerpost',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='showbiz',
            name='body2',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='showbiz',
            name='body3',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='showbiz',
            name='image2',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='showbiz',
            name='image3',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='showbiz',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='sport',
            name='body2',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='sport',
            name='body3',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='sport',
            name='image2',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sport',
            name='image3',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='sport',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='tech',
            name='body2',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='tech',
            name='body3',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='tech',
            name='image2',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tech',
            name='image3',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tech',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=' '),
        ),
        migrations.AddField(
            model_name='travel',
            name='body2',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='travel',
            name='body3',
            field=models.CharField(blank=True, default=' ', max_length=10000),
        ),
        migrations.AddField(
            model_name='travel',
            name='image2',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='travel',
            name='image3',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='travel',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='headerpost',
            name='title',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='showbiz',
            name='title',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='sport',
            name='title',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='tech',
            name='title',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=555),
        ),
    ]
