# Generated by Django 4.1 on 2022-09-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerpost',
            name='title',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='showbiz',
            name='title',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='sport',
            name='title',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='tech',
            name='title',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title',
            field=models.CharField(max_length=155),
        ),
    ]
