# Generated by Django 4.2.2 on 2023-07-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_headerpost_title_alter_showbiz_title_and_more'),
        ('posts', '0002_headerpost_body2_headerpost_body3_headerpost_image2_and_more'),
    ]

    operations = [
    ]
