# Generated by Django 4.2.2 on 2023-07-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_merge_20230702_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headerpost',
            name='title',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='showbiz',
            name='title',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='sport',
            name='title',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='tech',
            name='title',
            field=models.CharField(max_length=555),
        ),
        migrations.AlterField(
            model_name='travel',
            name='title',
            field=models.CharField(max_length=555),
        ),
    ]
