# Generated by Django 4.1 on 2022-08-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='prefix',
            field=models.CharField(blank=True, default='prefixiiii', max_length=320),
        ),
    ]
