# Generated by Django 4.1 on 2022-08-22 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(max_length=55, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=55)),
                ('body', models.CharField(max_length=10000)),
                ('category', models.CharField(default=None, max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
