# Generated by Django 4.1 on 2022-08-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
