# Generated by Django 4.1 on 2022-08-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showbiz',
            name='category',
            field=models.CharField(default='Showbiz', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.CharField(default='Sport', max_length=1000),
        ),
        migrations.AlterField(
            model_name='travel',
            name='category',
            field=models.CharField(default='Travel', max_length=1000),
        ),
    ]
