# Generated by Django 4.2.4 on 2023-08-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.CharField(default=' ', max_length=1000, primary_key=True, serialize=True)),
                ('name', models.CharField(default=' ', max_length=1000)),
                ('authors', models.CharField(default=' ', max_length=1000)),
                ('title', models.CharField(default=' ', max_length=1000)),
                ('comments', models.CharField(default=' ', max_length=1000)),
                ('journal_ref', models.CharField(default=' ', max_length=1000)),
                ('doi', models.CharField(default=' ', max_length=1000)),
                ('report_no', models.CharField(default=' ', max_length=1000)),
                ('categories', models.CharField(default=' ', max_length=1000)),
                ('license', models.CharField(default=' ', max_length=1000)),
                ('abstract', models.CharField(default=' ', max_length=1000)),
                ('authors_parsed', models.CharField(default=' ', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=True, verbose_name='ID')),
                ('title', models.CharField(default=' ', max_length=200)),
                ('abstract', models.TextField(default=' ')),
                ('authors', models.ManyToManyField(default=' ', to='app.author')),
            ],
        ),
    ]
