# Generated by Django 4.1 on 2022-08-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('body', models.CharField(max_length=10000)),
                ('category', models.CharField(default=None, max_length=1000)),
                ('image', models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/images/No_image/No_image_available.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='prefix',
            field=models.CharField(blank=True, default=None, max_length=320),
        ),
    ]
