# Generated by Django 4.1 on 2022-08-21 01:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_headerpost_alter_post_category_alter_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerpost',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
