# Generated by Django 4.1 on 2022-08-26 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_showbiz_category_alter_sport_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Tech',
        ),
    ]
